version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nasadb
      PG_DATA: /data/postgres
    ports:
      - "5432:5432"
